# Generated by Django 4.2.25 on 2025-11-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_tabela', models.CharField(default='com-recebimento', max_length=50)),
                ('origem_id', models.IntegerField(help_text='nIdReceb')),
                ('destino_tabela', models.CharField(default='conta_a_pagar', max_length=50)),
                ('destino_id', models.IntegerField(help_text='nCodTitulo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('success', 'Sucesso'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('tentativas', models.IntegerField(default=0)),
                ('max_tentativas', models.IntegerField(default=3)),
                ('anexos_transferidos', models.JSONField(blank=True, default=list)),
                ('total_anexos', models.IntegerField(default=0)),
                ('anexos_sucesso', models.IntegerField(default=0)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attachment_transfer_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['origem_id', 'destino_id'], name='attachment__origem__322b0d_idx'), models.Index(fields=['status'], name='attachment__status_0636ca_idx'), models.Index(fields=['created_at'], name='attachment__created_da1a62_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttachmentIntegrationMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem_recebimento_id', models.IntegerField(db_index=True, help_text='nIdReceb')),
                ('destino_conta_pagar_id', models.IntegerField(db_index=True, help_text='nCodTitulo')),
                ('numero_nf', models.CharField(blank=True, max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attachment_integration_map',
                'indexes': [models.Index(fields=['origem_recebimento_id'], name='attachment__origem__d4226d_idx'), models.Index(fields=['destino_conta_pagar_id'], name='attachment__destino_eb84d7_idx'), models.Index(fields=['created_at'], name='attachment__created_35af0c_idx')],
                'unique_together': {('origem_recebimento_id', 'destino_conta_pagar_id')},
            },
        ),
    ]
