# Generated by Django 4.2.25 on 2025-11-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderClosureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50)),
                ('item_pedido', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_nf_servico', models.CharField(max_length=50)),
                ('id_nf_servico', models.IntegerField(help_text='ID da NF de serviço no Omie')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('success', 'Sucesso'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('tentativas', models.IntegerField(default=0)),
                ('max_tentativas', models.IntegerField(default=3)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'purchase_order_closure_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['numero_pedido'], name='purchase_or_numero__03776a_idx'), models.Index(fields=['status'], name='purchase_or_status_fd4749_idx'), models.Index(fields=['created_at'], name='purchase_or_created_6b2383_idx')],
            },
        ),
    ]
